apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ams6u7tad-java-springboot
  janus-idp.io/tekton: ams6u7tad-java-springboot
  backstage.io/kubernetes-id: ams6u7tad-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ams6u7tad-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
